### ISSUE TITLE
Attempted import error: 'log' is not exported from 'polyrhythm'

### ISSUE THREAD

**Issue by justinramel** [deanius/polyrhythm-react#1]
Hey @deanius great library! 

Just working through the docs and hit an issue. Trying to use inside a create-react-app, I get the error:

```
./node_modules/polyrhythm-react/dist/polyrhythm-react.esm.js
Attempted import error: 'log' is not exported from 'polyrhythm'
```

Looks like the `polyrhythm` has dropped the `log` export but `polyrhythm-react` is still expecting it.

Happy to help debug the issue, if you need anymore info let me know 😄 

Versions:
```
macOS Catalina - 10.15.7

$ node -v
v14.11.0
$ npm -v
7.5.2
```

**Comment by deanius** [comment]
Justin - fixed in the newest build, thanks for filing the issue. Would you mind sharing what you're trying to use it for?

**Comment by justinramel** [comment]
Working thanks 😀

I'm using it very simply for cross component communication. I have web sock messages coming in that I push out to a a few components that have listeners.  

As soon as I get some time I want to dig into your docs (which are excellent by the way) and use it to its full potential!
